site_name: stlyx Coding Book
site_url: http://tx.stlyx.cn/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 切换到自动模式
  font:
    text: Noto Sans SC
    code: Source Code Pro
  language: zh
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.footer
    - content.code.select
    - content.code.copy
copyright: Copyright &copy; 2024 stlyx
extra:
  generator: false
markdown_extensions:
  - footnotes
  - tables
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
